// Copyright 2014 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package types

import (
	"io"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/rlp"
)

//go:generate gencodec -type Log -field-override logMarshaling -out gen_log_json.go

// Log represents a contract log event. These events are generated by the LOG opcode and
// stored/indexed by the node.
// Log는 계약의 로그 이벤트를 나타낸다. 이벤트들은 LOG opcode와 노드의 저장 및 색인에 의해 생성된다
type Log struct {
	// Consensus fields:
	// address of the contract that generated the event
	// 합의 필드
	// 이벤트를 생성한 계약주소
	Address common.Address `json:"address" gencodec:"required"`
	// list of topics provided by the contract.
	// 계약에 의해 제공된 토픽의 리스트
	Topics []common.Hash `json:"topics" gencodec:"required"`
	// supplied by the contract, usually ABI-encoded
	// 계약에 의해 제공된 데이터. 일반적으로 encoding된 ABI
	Data []byte `json:"data" gencodec:"required"`

	// Derived fields. These fields are filled in by the node
	// but not secured by consensus.
	// block in which the transaction was included
	// 유도된 필드. 이필드들은 노드에의해 채워지지만 합의에 의해 보호되지는 않는다
	// 트렌젝션이 포함된 블록번호
	BlockNumber uint64 `json:"blockNumber"`
	// hash of the transaction
	// 트렌젝션의 해시
	TxHash common.Hash `json:"transactionHash" gencodec:"required"`
	// index of the transaction in the block
	// 블록상의 트렌젝션 인덱스
	TxIndex uint `json:"transactionIndex" gencodec:"required"`
	// hash of the block in which the transaction was included
	// 트렌젝션이 포함된 블록의 해시
	BlockHash common.Hash `json:"blockHash"`
	// index of the log in the receipt
	// 영수증의 로그 인덱스
	Index uint `json:"logIndex" gencodec:"required"`

	// The Removed field is true if this log was reverted due to a chain reorganisation.
	// You must pay attention to this field if you receive logs through a filter query.
	// Removed필드는 체인의 제구성으로 로그가 복구되었을때 true이다.
	// 필터쿼리를 통해 로그를 받았을때 이필드를 반드시 참조해야 한다
	Removed bool `json:"removed"`
}

type logMarshaling struct {
	Data        hexutil.Bytes
	BlockNumber hexutil.Uint64
	TxIndex     hexutil.Uint
	Index       hexutil.Uint
}

type rlpLog struct {
	Address common.Address
	Topics  []common.Hash
	Data    []byte
}

type rlpStorageLog struct {
	Address     common.Address
	Topics      []common.Hash
	Data        []byte
	BlockNumber uint64
	TxHash      common.Hash
	TxIndex     uint
	BlockHash   common.Hash
	Index       uint
}

// EncodeRLP implements rlp.Encoder.
// EncodeRLP함수는 rlp.Encoder를 구현한다
func (l *Log) EncodeRLP(w io.Writer) error {
	return rlp.Encode(w, rlpLog{Address: l.Address, Topics: l.Topics, Data: l.Data})
}

// DecodeRLP implements rlp.Decoder.
// DecodeRLP함수는 rlp.Decoder를 구현한다
func (l *Log) DecodeRLP(s *rlp.Stream) error {
	var dec rlpLog
	err := s.Decode(&dec)
	if err == nil {
		l.Address, l.Topics, l.Data = dec.Address, dec.Topics, dec.Data
	}
	return err
}

// LogForStorage is a wrapper around a Log that flattens and parses the entire content of
// a log including non-consensus fields.
// LogForStorage는 합의 필드가 아닌 로그의 전체 컨텐츠를 분석하고 평활화 로그를 포함한다
type LogForStorage Log

// EncodeRLP implements rlp.Encoder.
// EncodeRLP함수는 rlp.Encoder를 구현한다
func (l *LogForStorage) EncodeRLP(w io.Writer) error {
	return rlp.Encode(w, rlpStorageLog{
		Address:     l.Address,
		Topics:      l.Topics,
		Data:        l.Data,
		BlockNumber: l.BlockNumber,
		TxHash:      l.TxHash,
		TxIndex:     l.TxIndex,
		BlockHash:   l.BlockHash,
		Index:       l.Index,
	})
}

// DecodeRLP implements rlp.Decoder.
// DecodeRLP함수는 rlp.Decoder를 구현한다
func (l *LogForStorage) DecodeRLP(s *rlp.Stream) error {
	var dec rlpStorageLog
	err := s.Decode(&dec)
	if err == nil {
		*l = LogForStorage{
			Address:     dec.Address,
			Topics:      dec.Topics,
			Data:        dec.Data,
			BlockNumber: dec.BlockNumber,
			TxHash:      dec.TxHash,
			TxIndex:     dec.TxIndex,
			BlockHash:   dec.BlockHash,
			Index:       dec.Index,
		}
	}
	return err
}
